CUDNN_BENCHMARK: false
datamodule:
  name: cityscapes
  args:
    crop_size:
    - 1024
    - 512
    base_size:
    - 1024
    - 512
    base_size_val:
    - 2048
    - 1024
    scale_range:
    - 1.0
    - 2.0
    single_category_max_area: 1.0
    target_type:
    - semantic
    - instance
    data_dir: ~/Datasets/Cityscapes
    batch_size: 16
    val_batch_size: 1
    collate_name: mask2former
    panoptic_preprocessing: mask2former
    flip: true
    persistent_workers: false
module:
  model:
    name: mask2former
    DETECTIONS_PER_IMAGE: 100
    ANCHOR_GENERATOR:
      ANGLES:
      - - -90
        - 0
        - 90
      ASPECT_RATIOS:
      - - 0.5
        - 1.0
        - 2.0
      NAME: DefaultAnchorGenerator
      OFFSET: 0.0
      SIZES:
      - - 32
        - 64
        - 128
        - 256
        - 512
    backbone:
      name: resnet50
      output_stride: 32
      pretrained_backbone: false
      backbone_file: ~/Experiments/checkpoints/resnet50_hollistic.pth
    DEVICE: cuda
    FPN:
      FUSE_TYPE: sum
      IN_FEATURES: []
      NORM: ''
      OUT_CHANNELS: 256
    KEYPOINT_ON: false
    LOAD_PROPOSALS: false
    args:
      DETECTIONS_PER_IMAGE: 100
      DEC_LAYERS: 10
      DIM_FEEDFORWARD: 2048
      DROPOUT: 0.0
      ENC_LAYERS: 0
      ENFORCE_INPUT_PROJ: false
      HIDDEN_DIM: 256
      NHEADS: 8
      NUM_OBJECT_QUERIES: 100
      PRE_NORM: false
      SIZE_DIVISIBILITY: 32
      TRANSFORMER_DECODER_NAME: MultiScaleMaskedTransformerDecoder
      TRANSFORMER_IN_FEATURE: multi_scale_pixel_decoder
      TEST:
        OBJECT_MASK_THRESHOLD: 0.5
        OVERLAP_THRESHOLD: 0.8
        PANOPTIC_ON: true
        INSTANCE_ON: false
        SEMANTIC_ON: true
        SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: false
      losses:
        mask:
          name: mask2former
          args:
            deep_supervision: true
            eos_coef: 0.1
            class_weight: 2.0
            dice_weight: 5.0
            mask_weight: 0.1
            dec_layers: 10
            num_points: 12544
            oversample_ratio: 3.0
            importance_sample_ratio: 0.75
            weight_dict_method: null
            mask_loss: likelihood
            mask_embed_type: beta
            double_dice: true
            positive_label_sample_ratio: 0.3
            losses:
            - labels
            - masks
          weight: 1
      split_rows: 2
      class_embed:
        name: linear
        args:
          hidden_dim: 256
          num_classes: 20
      mask_embed_type: beta
      num_classes: 19
    MASK_ON: false
    META_ARCHITECTURE: MaskFormer
    SEM_SEG_HEAD:
      ASPP_CHANNELS: 256
      ASPP_DILATIONS:
      - 6
      - 12
      - 18
      ASPP_DROPOUT: 0.1
      COMMON_STRIDE: 4
      CONVS_DIM: 256
      DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES:
      - res3
      - res4
      - res5
      DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
      DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
      IGNORE_VALUE: 255
      IN_FEATURES:
      - res2
      - res3
      - res4
      - res5
      LOSS_TYPE: hard_pixel_mining
      LOSS_WEIGHT: 1.0
      MASK_DIM: 256
      NAME: MaskFormerHead
      NORM: GN
      NUM_CLASSES: 19
      PIXEL_DECODER_NAME: MSDeformAttnPixelDecoder
      PROJECT_CHANNELS:
      - 48
      PROJECT_FEATURES:
      - res2
      TRANSFORMER_ENC_LAYERS: 6
      USE_DEPTHWISE_SEPARABLE_CONV: false
    PANOPTIC_FPN:
      COMBINE:
        ENABLED: true
        INSTANCES_CONFIDENCE_THRESH: 0.5
        OVERLAP_THRESH: 0.5
        STUFF_AREA_LIMIT: 4096
      INSTANCE_LOSS_WEIGHT: 1.0
    PROPOSAL_GENERATOR:
      MIN_SIZE: 0
      NAME: RPN
  optimizer:
    type: adamw
    args:
      lr: 0.0001
      weight_decay: 0.05
    lr_scheduler:
      type: polynomial
      args:
        power: 0.9
        total_iters: 90
    WEIGHT_DECAY_NORM: 0.0
    WEIGHT_DECAY_EMBED: 0
    backbone_lr_factor: 0.1
    name: adamw
  log_folder: sampling/config_softmax_prototype_beta_1728494775.6130967
trainer:
  trainer_args:
    gradient_clip_val: 0.01
    gradient_clip_algorithm: norm
  checkpoint:
    monitor: val_iou
    mode: max
    save_last: true
  max_epochs: 90
  val_interval: 10
  val_check_interval: 1.0
  num_sanity_val_steps: 0
  gpus: 1
  tracking_uri: ""
experiment_name: sampling
type: panoptic
experiment_folder: null
run_name: config_softmax_prototype_beta_1728494775.6130967